describe ('Clicks on My Account', function(){
      // Valid data 
    it("Added details successfully", function(){
        cy.visit('/')
        cy.get('#username')
        .type('Thanos.S')
        cy.get('#password')  
        .type('Gul12')
        cy.get('.MuiButton-label').click()
        cy.get('[data-test=sidenav-user-settings] > .MuiListItemText-root > .MuiTypography-root').click()
        cy.get('[data-test=user-settings-firstName-input]')
        .type('Gul')
        cy.get('[data-test=user-settings-lastName-input]')
        .type('S')
        cy.get('[data-test=user-settings-email-input]')
        .type('gul@gmail.com')
        cy.get('[data-test=user-settings-phoneNumber-input]')
        .type('9393121232')
        cy.get('[data-test=user-settings-submit]').click()
    })
});

// Invalid Phone number 

it("Invalid Phone number", function(){
    cy.visit('/')
    cy.get('#username')
    .type('Thanos.S')
    cy.get('#password')  
    .type('Gul12')
    cy.get('.MuiButton-label').click()
    cy.get('[data-test=sidenav-user-settings] > .MuiListItemText-root > .MuiTypography-root').click()
    cy.get('[data-test=user-settings-firstName-input]')
    .focus()
    .blur()
    .type('Gul')
    cy.get('[data-test=user-settings-lastName-input]')
    .type('S')
    cy.get('[data-test=user-settings-email-input]')
    .type('gul@gmail.com')
    cy.get('[data-test=user-settings-phoneNumber-input]')
    .type('939123')
    cy.get('#user-settings-phoneNumber-input-helper-text')
})

// Invalid email id 
it("Invalid email id", function(){
    cy.visit('/')
    cy.get('#username')
    .type('Thanos.S')
    cy.get('#password')  
    .type('Gul12')
    cy.get('.MuiButton-label').click()
    cy.get('[data-test=sidenav-user-settings] > .MuiListItemText-root > .MuiTypography-root').click()
    cy.get('[data-test=user-settings-firstName-input]')
    .type('Gul')
    cy.get('[data-test=user-settings-lastName-input]')
    .type('S')
    cy.get('[data-test=user-settings-email-input]')
    .type('gulgmail.com')
    cy.get('#user-settings-email-input-helper-text') 
})

// Blank first name 
it("Blank first name", function(){
    cy.visit('/')
    cy.get('#username')
    .type('Thanos.S')
    cy.get('#password')  
    .type('Gul12')
    cy.get('.MuiButton-label').click()
    cy.get('[data-test=sidenav-user-settings] > .MuiListItemText-root > .MuiTypography-root').click()
    cy.get('[data-test=user-settings-firstName-input]')
    .focus()
    .blur()
    .click()
})

// Blank last name
it("Blank last name", function(){
    cy.visit('/')
    cy.get('#username')
    .type('Thanos.S')
    cy.get('#password')  
    .type('Gul12')
    cy.get('.MuiButton-label').click()
    cy.get('[data-test=sidenav-user-settings] > .MuiListItemText-root > .MuiTypography-root').click()
    cy.get('[data-test=user-settings-firstName-input]')
    .type('Gul')
    cy.get('[data-test=user-settings-lastName-input]')
    .focus()
    .blur()
    .click()
})

// Blank email id field 
it("Blank email id field", function(){
    cy.visit('/')
    cy.get('#username')
    .type('Thanos.S')
    cy.get('#password')  
    .type('Gul12')
    cy.get('.MuiButton-label').click()
    cy.get('[data-test=sidenav-user-settings] > .MuiListItemText-root > .MuiTypography-root').click()
    cy.get('[data-test=user-settings-firstName-input]')
    .type('Gul')
    cy.get('[data-test=user-settings-lastName-input]')
    .type('S')
    cy.get('[data-test=user-settings-email-input]')
    .focus()
    .blur()
    .click()
})

// Blank phone number field
it("Blank phone number field", function(){
    cy.visit('/')
    cy.get('#username')
    .type('Thanos.S')
    cy.get('#password')  
    .type('Gul12')
    cy.get('.MuiButton-label').click()
    cy.get('[data-test=sidenav-user-settings] > .MuiListItemText-root > .MuiTypography-root').click()
    cy.get('[data-test=user-settings-firstName-input]')
    .type('Gul')
    cy.get('[data-test=user-settings-lastName-input]')
    .type('S')
    cy.get('[data-test=user-settings-email-input]')
    .type('gul@gmail.com')
    cy.get('[data-test=user-settings-phoneNumber-input]')
    .focus()
    .blur()
    .click()
})

// All blank fields 
it("Blank first name", function(){
    cy.visit('/')
    cy.get('#username')
    .type('Thanos.S')
    cy.get('#password')  
    .type('Gul12')
    cy.get('.MuiButton-label').click()
    cy.get('[data-test=sidenav-user-settings] > .MuiListItemText-root > .MuiTypography-root').click()
    cy.get('[data-test=user-settings-firstName-input]')
    .focus()
    .blur()
    .click()
    cy.get('[data-test=user-settings-lastName-input]')
    .focus()
    .blur()
    .click()
    cy.get('[data-test=user-settings-email-input]')
    .focus()
    .blur()
    .click()
    cy.get('[data-test=user-settings-phoneNumber-input]')
    .focus()
    .blur()
    .click()
})